### ISSUE TITLE
Venue added for event is removed when event is updated

### ISSUE THREAD

**Issue by bondletta** [stephenharris/Event-Organiser#324] opened 2016-01-17 05:31 UTC
When a venue is added for an event and the Update button is clicked to save the event, the event venue shows as expected (good). But if the Update button is clicked again, the added venue no longer shows (bad).

**Comment by stephenharris** [comment] 2016-01-18 21:30
Thanks @bondletta - I've just confirmed this, and will follow up with a fix. Just to confirm, you are using 3.0.0-beta?

**Comment by bondletta** [comment] 2016-01-18 22:36
Yes, using the beta.
Bond 

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 18, 2016 at 3:30 PM, Stephen Harris<notifications@github.com> wrote:   
Thanks @bondletta - I've just confirmed this, and will follow up with a fix. Just to confirm, you are using 3.0.0-beta?

**Comment by stephenharris** [comment] 2016-01-21 07:54
This is fixed in 3.0.0-rc-1, and I'll be porting the fix to 2.13.8

**Comment by stephenharris** [comment] 2016-01-25 21:45
Just to follow up on this. This was not a bug in 2.13.*, so closing.

**Closed by stephenharris** 2016-01-25 21:45 UTC
Labels: bug
