### ISSUE TITLE
Events are showing that shouldn't be when querying using 'ondate'

### ISSUE THREAD

**Issue by HandHugs** [stephenharris/Event-Organiser#246] opened 2015-03-03 05:37 UTC
I have a weird problem!

Here is my query:

    $events = eo_get_events(array(
                         'numberposts'=>-1,
                         'ondate'=>  '2015-03-25'
                  ));

but as you can see on this test page that echoes the events, there is a repeating event that doesn't occur on that date at all, still showing not only one but several of it's other dates as well. When I change the date, sometimes it shows those  events too, and sometimes not.. I can't really figure out the pattern. Anyway I know they aren't supposed to be there. Can you help?

https://posterchildevents.com/testing/

**Comment by stephenharris** [comment] 2015-03-04 20:27
That query will show all events *running* that day. Each occurrence of the event "The Sanctuary at Sandy Plaza" is actually a month long. The event starts on the 12th March and ends on the 12th April and is repeated. So the occurrences are:

 1.12th March - 12th April
 2.13th March - 13th April
 3.14th March - 14th April

and so on. So each of those occurrences are in fact running on the 25th March.

When creating the event, the end date is the end date of the first occurrence, and the event is then repeated according to the schedule provided (with each occurrence having the same duration) until the specified "until" date.

**Comment by stephenharris** [comment] 2015-04-06 10:40
Closing this as I think the issue is resolved. Feel free to re-open if not.

**Closed by stephenharris** 2015-04-06 10:40 UTC
